# Generated by Django 5.0.1 on 2024-03-01 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApi', '0003_remove_route_places_remove_route_owner_delete_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('owners', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApi.busowner')),
            ],
        ),
        migrations.CreateModel(
            name='Busstop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('owners', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApi.busowner')),
                ('routes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApi.route')),
            ],
        ),
    ]
