# Generated by Django 5.0.1 on 2024-03-01 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApi', '0004_route_busstop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busstop',
            name='owners',
        ),
        migrations.RemoveField(
            model_name='route',
            name='owners',
        ),
    ]
