# Generated by Django 5.0.1 on 2024-03-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApi', '0005_remove_busstop_owners_remove_route_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='busowner',
            name='is_approved',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='busowner',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
