# Generated by Django 5.0.1 on 2024-03-01 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApi', '0006_busowner_is_approved_busowner_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('license', models.FileField(upload_to='license')),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('busowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApi.busowner')),
            ],
        ),
    ]
