# Generated by Django 5.0.1 on 2024-03-01 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApi', '0007_busdriver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bus',
        ),
    ]
