# Generated by Django 5.0.1 on 2024-03-01 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApi', '0008_delete_bus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('Number_plate', models.CharField(max_length=500)),
                ('Engine_no', models.IntegerField()),
                ('RC_book', models.ImageField(null=True, upload_to='license')),
                ('is_active', models.BooleanField(default=True)),
                ('busowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApi.busowner')),
            ],
        ),
    ]
