# Generated by Django 4.2.5 on 2024-03-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApi', '0010_rename_name_busstop_stop_name_busstop_approx_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='ends_at',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='starts_from',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='time_taken',
            field=models.TimeField(),
        ),
    ]
