# Generated by Django 4.2.5 on 2024-03-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApi', '0011_route_ends_at_route_starts_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='ends_at',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='route',
            name='starts_from',
            field=models.CharField(max_length=200),
        ),
    ]
