# Generated by Django 4.2.5 on 2024-03-07 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApi', '0015_remove_routeassign_date_alter_routeassign_busowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeassign',
            name='busdriver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApi.busdriver'),
        ),
    ]
