# Generated by Django 4.2.5 on 2024-03-07 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApi', '0016_routeassign_busdriver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeassign',
            name='busdriver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApi.busdriver'),
        ),
    ]
