# Generated by Django 4.2.5 on 2024-03-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApi', '0017_alter_routeassign_busdriver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='RC_book',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='busdriver',
            name='license',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='busowner',
            name='proof',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
